# Generated by Django 4.2.6 on 2023-11-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='like',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='like',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
