# Generated by Django 4.2.6 on 2023-11-11 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rated_by',
            field=models.ManyToManyField(blank=True, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
